spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lio_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  type-aliases-package: com.lio.system.domain,com.lio.web.domain

mapper:
  mappers: com.lio.common.config.MyMapper
  not-empty: false
  identity: myql
